# Data Cleaning

## 1. Load the Dataset

In [24]:
import pandas as pd

df = pd.read_csv("Sample-Superstore.csv",encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## 2. Handle null and duplicates

In [25]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [26]:
print(int(df.duplicated().sum()))

0

In [27]:
df=df.drop_duplicates()

In [28]:
print(int(df.duplicated().sum()))

0

## 3. Data type conversion

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

### As we can see order date and ship date are in object type---> date type

In [30]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Data transformation

## 1. Normalization

In [31]:
from sklearn.preprocessing import MinMaxScaler

## Min max normalization

scaler = MinMaxScaler()
df[['Sales_Normalized', 'Profit_Normalized']] = scaler.fit_transform(df[['Sales', 'Profit']])

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             9994 non-null   int64
 1   Order ID           9994 non-null   object
 2   Order Date         9994 non-null   datetime64[ns]
 3   Ship Date          9994 non-null   datetime64[ns]
 4   Ship Mode          9994 non-null   object
 5   Customer ID        9994 non-null   object
 6   Customer Name      9994 non-null   object
 7   Segment            9994 non-null   object
 8   Country            9994 non-null   object
 9   City               9994 non-null   object
 10  State              9994 non-null   object
 11  Postal Code        9994 non-null   int64
 12  Region             9994 non-null   object
 13  Product ID         9994 non-null   object
 14  Category           9994 non-null   object
 15  Sub-Category       9994 non-null   object
 16  Product Name       9994 non-null   object
 17  Sales              9994 non-null   float64
 18  Quantity           9994 non-null   int64
 19  Discount           9994 non-null   float64
 20  Profit             9994 non-null   float64
 21  Sales_Normalized   9994 non-null   float64
 22  Profit_Normalized  9994 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(3), object(13)
memory usage: 1.8+ MB

### Feature Engineering

In [33]:
# Extract time features
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Month_Name'] = df['Order Date'].dt.month_name()

# Profit margin
df['Profit_Margin'] = df['Profit'] / df['Sales']

In [34]:
# Pareto analysis
product_sales = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False)
product_sales_cum = product_sales.cumsum() / product_sales.sum()

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             9994 non-null   int64
 1   Order ID           9994 non-null   object
 2   Order Date         9994 non-null   datetime64[ns]
 3   Ship Date          9994 non-null   datetime64[ns]
 4   Ship Mode          9994 non-null   object
 5   Customer ID        9994 non-null   object
 6   Customer Name      9994 non-null   object
 7   Segment            9994 non-null   object
 8   Country            9994 non-null   object
 9   City               9994 non-null   object
 10  State              9994 non-null   object
 11  Postal Code        9994 non-null   int64
 12  Region             9994 non-null   object
 13  Product ID         9994 non-null   object
 14  Category           9994 non-null   object
 15  Sub-Category       9994 non-null   object
 16  Product Name       9994 non-null   object
 17  Sales              9994 non-null   float64
 18  Quantity           9994 non-null   int64
 19  Discount           9994 non-null   float64
 20  Profit             9994 non-null   float64
 21  Sales_Normalized   9994 non-null   float64
 22  Profit_Normalized  9994 non-null   float64
 23  Year               9994 non-null   int32
 24  Month              9994 non-null   int32
 25  Month_Name         9994 non-null   object
 26  Profit_Margin      9994 non-null   float64
dtypes: datetime64[ns](2), float64(6), int32(2), int64(3), object(14)
memory usage: 2.0+ MB

In [36]:
columns_to_drop = [
    'Row ID', 'Order ID', 'Customer ID', 'Customer Name',
    'Product ID', 'Country', 'Ship Date', 'Ship Mode', 'Postal Code'
]
df_final = df.drop(columns=columns_to_drop)
df_final.head()

,Order Date,Segment,City,State,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales_Normalized,Profit_Normalized,Year,Month,Month_Name,Profit_Margin
0,2016-11-08,Consumer,Henderson,Kentucky,South,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.011552,0.442794,2016,11,November,0.1600
1,2016-11-08,Consumer,Henderson,Kentucky,South,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.032313,0.454639,2016,11,November,0.3000
2,2016-06-12,Corporate,Los Angeles,California,West,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.000626,0.440458,2016,6,June,0.4700
3,2015-10-11,Consumer,Fort Lauderdale,Florida,South,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,0.042280,0.414464,2015,10,October,-0.4000
4,2015-10-11,Consumer,Fort Lauderdale,Florida,South,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.000968,0.440168,2015,10,October,0.1125

In [37]:
df_final.to_csv("final_superstore_dashboard.csv", index=False)